apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: mdt-exporter
  name: mdt-exporter
spec:
  replicas: 1
  selector:
    deploymentconfig: mdt-exporter
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: mdt-exporter
        deploymentconfig: mdt-exporter
    spec:
      containers:
        - image: >-
            docker-registry.default.svc:5000/dev/mdt-exporter:latest
          imagePullPolicy: Always
          name: exporter
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - exporter
        from:
          kind: ImageStreamTag
          name: 'mdt-exporter:latest'
          namespace: dev
      type: ImageChange
    - type: ConfigChange
