apiVersion: v1
kind: Service
metadata:
  name: mdt-exporter-svc
  labels:
    k8s-app: mdt-exporter
spec:
  ports:
  - name: mdt-metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    k8s-app: mdt-exporter
