---
# Currently not working. Openshift cluster operator doesn't notice it when it get's created.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mdt-exporter
  # Change this to the namespace the Prometheus instance is running in
  namespace: openshift-monitoring
  labels:
    k8s-app: mdt-exporter
spec:
  selector:
    matchLabels:
      k8s-app: mdt-exporter
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    port: mdt-metrics
    scheme: http
  jobLabel: mtdparser
